notifications:
  email: false
language: cpp

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode6.4

branches:
  only:
  - master
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-4.9
      - gfortran-4.9
      - liblapack-dev
      - clang-3.8
      - sox

branches:
  only:
    - master
    - pybind11

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sox python3; fi
  
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  
before_script:
  - cd tools
  - extras/check_dependencies.sh
  - make -j 4
  - make openblas
  - cd ..
  
script:
  # See http://petereisentraut.blogspot.com/2011/05/ccache-and-clang.html and
  # http://peter.eisentraut.org/blog/2014/12/01/ccache-and-clang-part-3/
  # for the explanation why extra switches needed for clang with ccache.
  - CXX="ccache clang++-3.8 -Qunused-arguments -fcolor-diagnostics -Wno-tautological-compare"
    CFLAGS=""
    LDFLAGS="-llapack -Wl,-fuse-ld=gold"
    INCDIRS="$XROOT/usr/include"
    LIBDIRS="$XROOT/usr/lib"
      tools/extras/travis_script.sh
#   To troubleshoot cache, add to above: CI_TARGETS=util CCACHE_LOGFILE=~/ccache.log

after_success:
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda/conda_upload.sh