notifications:
  email: false
language: cpp

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode6.4

branches:
  only:
  - master
  
before_script:
  - cd tools
  - extras/check_dependencies.sh
  - make -j 4
  - make openblas
  - cd ..
  
script:
  - make -j 4
  
deploy:
  provider: releases
  api_key:
    secure: sYKHcvBGCKvj5sX4yYLgEXhgEljCeuf7zI4R3T3vFzUjBa28brPODbRLC0oGuFbRa2dsLObNgYnDbH6YYxA6jFnf+gbUklfVJ8HRwji62IYcB/MPRZKT4ncb2Kqj2tHwgn8kGog/wstmH1Ay/d/A4zo8o+ugNz452fSL6ZMtt/jCXQsWTzoyus+s986KC74K68RKUxBoCLvXg1oa6y4l9D+rU/47iLgEfIle4gpn1PYphOqEHmrgix8eZo6JPuE5LGmtGaju3emM/S4jeblVgPdR+8rbXVnogi3lsTO5ScnwK0fyVaDlswkd0q4xlePhbkbiSX/Ym9y+89n22J9wQ57fXyTW0LMHdLEbCWdQbi7o2cTbfmHNsad21VN5aGHMIWXm2JFpbdF8VplWENhJ61ZmQ8eFpT/zfwvagO4/lfvmjxyeiZ2Vygqmpd07gosdICSwkW/lUVCatdBpLIw2vpsOaq0OffQAFexhqmdiI0kPS/DhKoSGMjpEiQSMeQ/0ns+9WJLQM3CA8Dv0N7UjBx76Il10WQQ/Wg9gaCU0SJOgJ1hQzUx2TPQ8bg5DXJUIKLIpmi9dmuXqx2MimKZosHnp1a6eYeGHHk125TMGXH19X8tvRVLoUn82m/jirwisWlPrzkHzsGd/otXMEgZef5oGUarq4LOpJX76pm1BoSY=
  file: kaldi_binaries.zip
  skip_cleanup: true
  on:
    repo: MontrealCorpusTools/kaldi
    tags: true
